# Data wrangling

Welcome to the fourth week of the course. By the end of this week, you should acquire:

**Knowledge on**:

* Data wrangling principles and practices
* Filtering, changing, grouping and joining data
* The pandas package


**Skills on**:

* Data wrangling principles and practices
* Filtering, changing, grouping and joining data
* The pandas package

# Working with pandas

In [1]:
import pandas as pd
#Creating dataframes with pandas
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns = ['Name', 'Age'])
df

   Name  Age
0   tom   10
1  nick   15
2  juli   14

In [12]:
#Importing data with pandas is incredibly easy
#Notice the sep argument, which stands for separator
apple_tweets = pd.read_csv("apple_tweets.csv", sep=",", encoding = 'unicode_escape')


#https://data.world/crowdflower/apple-twitter-sentiment

In [ ]:
#Writing data with pandas is also very easy
dataset.to_csv("filename.csv", sep="....")

# Pickles are useful for writing tuples, lists and dicts, but can also read dataframes

In [4]:
import pickle
your_data = {'foo': 'bar'}
# Store data (serialize)
with open('filename.pickle', 'wb') as handle:
    pickle.dump(your_data, handle)

# Load data (deserialize)
with open('filename.pickle', 'rb') as handle:
    my_data = pickle.load(handle)

my_data

{'foo': 'bar'}

In [6]:
user_sessions=pd.read_pickle("user_sessions.pkl")
user_sessions

,session_id,session_timestamp,user_agent,referral,paid_campaign,user_id
0,5555694754,2021-09-20 06:59:09,Mozilla/5.0 (Windows NT 6.2; lo-LA; rv:1.9.1.2...,google.com,1.0,NaN
1,5555694755,2021-09-23 19:07:17,Mozilla/5.0 (Windows; U; Windows NT 6.0) Apple...,instagram.com,4.0,NaN
2,5555694756,2021-09-25 14:12:23,Mozilla/5.0 (Android 2.3.6; Mobile; rv:7.0) Ge...,instagram.com,NaN,NaN
3,5555694757,2021-09-20 11:12:36,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,google.com,NaN,NaN
4,5555694758,2021-09-24 11:12:22,Opera/9.52.(X11; Linux i686; bho-IN) Presto/2....,google.com,2.0,NaN
...,...,...,...,...,...,...
49995,5555744749,2021-09-21 21:13:43,Mozilla/5.0 (Macintosh; PPC Mac OS X 10 5_1 rv...,morales-patel.com,4.0,NaN
49996,5555744750,2021-09-20 05:27:21,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,stark.com,1.0,NaN
49997,5555744751,2021-09-28 21:29:37,Mozilla/5.0 (Windows; U; Windows NT 6.1) Apple...,instagram.com,1.0,55886019
49998,5555744752,2021-09-25 19:33:29,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_1 like M...,google.com,NaN,NaN
49999,5555744753,2021-09-19 20:55:06,Mozilla/5.0 (Windows; U; Windows CE) AppleWebK...,webb.com,NaN,55886811

# Wrangling 101

In [3]:
#Get a feel for your dataset 
apple_tweets.head()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,sentiment,sentiment:confidence,date,id,query,sentiment_gold,text
0,623495513,True,golden,10,NaN,3,0.6264,Mon Dec 01 19:30:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\nnot_relevant,#AAPL:The 10 best Steve Jobs emails ever...htt...
1,623495514,True,golden,12,NaN,3,0.8129,Mon Dec 01 19:43:51 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\n1,RT @JPDesloges: Why AAPL Stock Had a Mini-Flas...
2,623495515,True,golden,10,NaN,3,1.0000,Mon Dec 01 19:50:28 +0000 2014,5.400000e+17,#AAPL OR @Apple,3,My cat only chews @apple cords. Such an #Apple...
3,623495516,True,golden,17,NaN,3,0.5848,Mon Dec 01 20:26:34 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\n1,I agree with @jimcramer that the #IndividualIn...
4,623495517,False,finalized,3,12/12/14 12:14,3,0.6474,Mon Dec 01 20:29:33 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Nobody expects the Spanish Inquisition #AAPL

In [8]:
len(apple_tweets)

3886

In [4]:
#print out all column names and see if there are any surprises
apple_tweets.columns

Index(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'sentiment', 'sentiment:confidence', 'date', 'id',
       'query', 'sentiment_gold', 'text'],
      dtype='object')

In [5]:
#Check column types 
apple_tweets.dtypes

_unit_id                  int64
_golden                    bool
_unit_state              object
_trusted_judgments        int64
_last_judgment_at        object
sentiment                object
sentiment:confidence    float64
date                     object
id                      float64
query                    object
sentiment_gold           object
text                     object
dtype: object

Notice above that last_judgement_at should really be a date of some kind, but it is not.

In [6]:
#Get a sense of the NA distribution in your dataset NaN
apple_tweets.isna().sum()

_unit_id                   0
_golden                    0
_unit_state                0
_trusted_judgments         0
_last_judgment_at        103
sentiment                  0
sentiment:confidence       0
date                       0
id                         0
query                      0
sentiment_gold          3783
text                       0
dtype: int64

In [13]:
#Drop missing values in a specific column
apple_tweets = apple_tweets.dropna(subset=["_last_judgment_at"])
apple_tweets.isna().sum()

_unit_id                   0
_golden                    0
_unit_state                0
_trusted_judgments         0
_last_judgment_at          0
sentiment                  0
sentiment:confidence       0
date                       0
id                         0
query                      0
sentiment_gold          3782
text                       0
dtype: int64

In [8]:
#Drop all missing values 
#apple_tweets = apple_tweets.dropna(how="any", inplace=True)

In [14]:
apple_tweets

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,sentiment,sentiment:confidence,date,id,query,sentiment_gold,text
4,623495517,False,finalized,3,12/12/14 12:14,3,0.6474,Mon Dec 01 20:29:33 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Nobody expects the Spanish Inquisition #AAPL
9,623495522,False,finalized,3,12/12/14 0:52,3,0.6360,Mon Dec 01 20:45:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,#AAPL:This Presentation Shows What Makes The W...
13,623495526,False,finalized,3,12/12/14 21:38,5,1.0000,Mon Dec 01 21:03:32 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @peterpham: Bought my @AugustSmartLock at t...
15,623495528,False,finalized,6,12/12/14 15:50,3,0.4798,Mon Dec 01 21:29:45 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,#aapl @applenws Thanks to the non factual dumb...
17,623495530,False,finalized,3,12/12/14 3:38,not_relevant,0.6904,Mon Dec 01 21:52:04 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@Apple John Cantlie has been a prisoner of ISI...
...,...,...,...,...,...,...,...,...,...,...,...,...
3876,623499406,False,finalized,3,12/12/14 2:08,3,1.0000,Tue Dec 09 21:21:12 +0000 2014,5.420000e+17,#AAPL OR @Apple,NaN,Apple Is Warming Up To Social Media: Apple is ...
3877,623499407,False,finalized,3,12/11/14 20:08,1,1.0000,Tue Dec 09 21:23:33 +0000 2014,5.420000e+17,#AAPL OR @Apple,NaN,Being held hostage at @apple - They are replac...
3878,623499408,False,finalized,3,12/12/14 3:32,5,0.6839,Tue Dec 09 21:24:22 +0000 2014,5.420000e+17,#AAPL OR @Apple,NaN,RT @shannonmmiller: Love the @Apple is support...
3879,623499409,False,finalized,6,12/11/14 20:50,not_relevant,0.6762,Tue Dec 09 21:27:06 +0000 2014,5.420000e+17,#AAPL OR @Apple,NaN,Tim Cook Met With Jesse Jackson for 'Positive ...
3880,623499410,False,finalized,3,12/12/14 2:58,1,0.6619,Tue Dec 09 21:28:07 +0000 2014,5.420000e+17,#AAPL OR @Apple,NaN,hey @apple is it normal for my laptop charger ...

In [ ]:
#Google .fillna() to get a sense of alternative approaches to dealing with NaN values

In [15]:
len(apple_tweets)

3783

# Filtering, selecting and renaming

Sometimes the dataset that you are working with contains lots of unncessery data. You will often want to filter (or subset) your dataset to include only: 
* some rows
* some columns 
* some values

In [17]:
#Let's start with dropping some rows since this dataset is quite large for dealing with 
#The command below selects the first 5000 rows
#We can use the len function to check that our operation worked as expected
apple_tweets = apple_tweets[:100]
len(apple_tweets)

100

In [18]:
#Remember that counting in Python starts at 0
apple_tweets = apple_tweets[0:50]
len(apple_tweets)

50

In [19]:
#Sometimes we want to drop certain column because we will not need them
apple_tweets = apple_tweets.drop(columns=["_unit_id", "_golden"])
apple_tweets
#Notice the inplace approach to dropping columns in the book. Inplace can come in handy in many cases

,_unit_state,_trusted_judgments,_last_judgment_at,sentiment,sentiment:confidence,date,id,query,sentiment_gold,text
4,finalized,3,12/12/14 12:14,3,0.6474,Mon Dec 01 20:29:33 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Nobody expects the Spanish Inquisition #AAPL
9,finalized,3,12/12/14 0:52,3,0.6360,Mon Dec 01 20:45:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,#AAPL:This Presentation Shows What Makes The W...
13,finalized,3,12/12/14 21:38,5,1.0000,Mon Dec 01 21:03:32 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @peterpham: Bought my @AugustSmartLock at t...
15,finalized,6,12/12/14 15:50,3,0.4798,Mon Dec 01 21:29:45 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,#aapl @applenws Thanks to the non factual dumb...
17,finalized,3,12/12/14 3:38,not_relevant,0.6904,Mon Dec 01 21:52:04 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@Apple John Cantlie has been a prisoner of ISI...
18,finalized,3,12/12/14 4:59,3,0.6621,Mon Dec 01 21:53:12 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@apple- thanks for xtra checkin at upper wests...
19,finalized,3,12/12/14 20:59,3,1.0000,Mon Dec 01 22:22:09 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Why #AAPL Stock Had a Mini-Flash Crash Today: ...
20,finalized,3,12/11/14 20:31,not_relevant,1.0000,Mon Dec 01 23:03:01 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,$AAPL dip only momentarily....just an aberrati...
21,finalized,4,12/12/14 8:36,3,0.7244,Mon Dec 01 23:12:40 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,The JH Hines Staff with their newly issued @ap...
22,finalized,3,12/12/14 14:08,3,0.6552,Mon Dec 01 23:43:14 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@robconeybeer: You need an IP portfolio to def...
27,finalized,4,12/12/14 8:36,3,0.7244,Tue Dec 02 00:15:14 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Justice Department cites 18th century federal ...
29,finalized,3,12/12/14 8:42,3,1.0000,Tue Dec 02 00:15:26 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
30,finalized,4,12/12/14 18:31,3,0.7179,Tue Dec 02 00:16:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Good be huge RT @thehill Justice Department ci...
31,finalized,3,12/12/14 2:33,3,1.0000,Tue Dec 02 00:16:04 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@thehill @Apple i cite the 4th amendment as a ...
32,finalized,3,12/12/14 0:01,3,0.6604,Tue Dec 02 00:16:27 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
33,finalized,4,12/11/14 23:40,5,1.0000,Tue Dec 02 00:17:02 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @saxonidubom: @rwang0 @Apple Thanks...think...
34,finalized,3,12/12/14 9:10,3,0.6515,Tue Dec 02 00:18:59 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
35,finalized,3,12/12/14 21:02,3,1.0000,Tue Dec 02 00:22:26 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Way to stay relevant RT @thehill: Justice Depa...
36,finalized,6,12/11/14 9:47,3,1.0000,Tue Dec 02 00:22:31 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Apple Inc. Flash Crash: What You Need to Know ...
38,finalized,3,12/11/14 14:07,3,1.0000,Tue Dec 02 00:24:26 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
39,finalized,6,12/12/14 9:26,1,0.4673,Tue Dec 02 00:24:47 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,That flash crash really screwed with a lot of ...
40,finalized,3,12/12/14 14:51,3,1.0000,Tue Dec 02 00:25:38 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @tra_hall: The JH Hines Staff with their ne...
42,finalized,3,12/12/14 3:33,3,1.0000,Tue Dec 02 00:27:36 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
43,finalized,3,12/11/14 22:17,1,0.6650,Tue Dec 02 00:28:38 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
45,finalized,3,12/11/14 21:20,3,1.0000,Tue Dec 02 00:31:26 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
46,finalized,6,12/11/14 20:50,1,0.5010,Tue Dec 02 00:32:42 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@thehill @Apple I cite the us constitution whe...
48,finalized,3,12/11/14 21:21,1,0.6672,Tue Dec 02 00:38:41 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@thehill @Apple Wish we could prosecute the ad...
49,finalized,3,12/12/14 20:51,3,1.0000,Tue Dec 02 00:39:47 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
50,finalized,3,12/12/14 1:20,3,0.6868,Tue Dec 02 00:39:51 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@thehill @Apple Furthermore there are no provi...
51,finalized,3,12/12/14 3:38,1,0.6656,Tue Dec 02 00:45:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,#AAPL:Here's why Apple dropped...http://t.co/q...
52,finalized,4,12/12/14 2:08,3,0.7408,Tue Dec 02 00:45:22 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,This one chart explains @tim_cook's affect on ...
53,finalized,3,12/12/14 2:28,3,1.0000,Tue Dec 02 00:47:23 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
54,finalized,3,12/12/14 21:02,3,1.0000,Tue Dec 02 00:47:46 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
55,finalized,4,12/12/14 22:25,3,0.7320,Tue Dec 02 00:51:10 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,"Final #AAPL #PutCallRatios for Monday, Decembe..."
56,finalized,3,12/12/14 17:48,3,0.7177,Tue Dec 02 00:53:22 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,#AAPL Launches Red #Apple Logo for World AIDS ...
59,finalized,3,12/12/14 8:52,1,1.0000,Tue Dec 02 00:56:11 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@apple why doesn't your people explain precaut...
60,finalized,3,12/11/14 20:59,3,1.0000,Tue Dec 02 00:56:43 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
61,finalized,3,12/12/14 11:16,3,0.6731,Tue Dec 02 00:59:49 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@Quailman_ @Apple u was bored huh
62,finalized,3,12/11/14 20:54,3,1.0000,Tue Dec 02 01:04:41 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @wagner_tim: @robconeybeer: You need an IP ...
64,finalized,3,12/12/14 20:54,1,1.0000,Tue Dec 02 01:06:42 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,@Apple made it clear today that I as a custome...
65,finalized,3,12/11/14 22:10,3,0.7011,Tue Dec 02 01:06:58 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,INSPI(RED) by @Apple and @tim_cook on #WorldAI...
66,finalized,4,12/12/14 2:39,3,0.7321,Tue Dec 02 01:07:53 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
67,finalized,3,12/12/14 9:14,3,1.0000,Tue Dec 02 01:09:53 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,16GB @Apple #iPad Air 2 Retina WiFi Tablet $40...
69,finalized,3,12/12/14 9:16,1,1.0000,Tue Dec 02 01:13:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Why does @Apple force people to use its VPN bu...
70,finalized,3,12/12/14 13:02,1,0.6398,Tue Dec 02 01:15:12 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Then how the hell did I take this screenshot? ...
71,finalized,3,12/12/14 3:17,3,1.0000,Tue Dec 02 01:17:55 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill Department cites 18th century fede...
72,finalized,3,12/12/14 1:13,3,0.6759,Tue Dec 02 01:22:40 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,RT @thehill: Justice Department cites 18th cen...
73,finalized,6,12/12/14 9:26,1,0.5327,Tue Dec 02 01:25:49 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Buy round lot on the open MT @WSJD #AAPL stock...
74,finalized,3,12/11/14 18:38,1,1.0000,Tue Dec 02 01:36:18 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,3G is draining my battery fix this @apple
75,finalized,3,12/11/14 18:42,not_relevant,0.6527,Tue Dec 02 01:36:35 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,My daughter's @Apple #iPod stolen. To the thie...

In [20]:
#We can alterntively choose which columns to keep
apple_tweets = apple_tweets[["_unit_state", "_trusted_judgments", "sentiment", "date", "id", "query", "text"]]
apple_tweets.columns

Index(['_unit_state', '_trusted_judgments', 'sentiment', 'date', 'id', 'query',
       'text'],
      dtype='object')

In [21]:
apple_tweets

,_unit_state,_trusted_judgments,sentiment,date,id,query,text
4,finalized,3,3,Mon Dec 01 20:29:33 +0000 2014,5.400000e+17,#AAPL OR @Apple,Nobody expects the Spanish Inquisition #AAPL
9,finalized,3,3,Mon Dec 01 20:45:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,#AAPL:This Presentation Shows What Makes The W...
13,finalized,3,5,Mon Dec 01 21:03:32 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @peterpham: Bought my @AugustSmartLock at t...
15,finalized,6,3,Mon Dec 01 21:29:45 +0000 2014,5.400000e+17,#AAPL OR @Apple,#aapl @applenws Thanks to the non factual dumb...
17,finalized,3,not_relevant,Mon Dec 01 21:52:04 +0000 2014,5.400000e+17,#AAPL OR @Apple,@Apple John Cantlie has been a prisoner of ISI...
18,finalized,3,3,Mon Dec 01 21:53:12 +0000 2014,5.400000e+17,#AAPL OR @Apple,@apple- thanks for xtra checkin at upper wests...
19,finalized,3,3,Mon Dec 01 22:22:09 +0000 2014,5.400000e+17,#AAPL OR @Apple,Why #AAPL Stock Had a Mini-Flash Crash Today: ...
20,finalized,3,not_relevant,Mon Dec 01 23:03:01 +0000 2014,5.400000e+17,#AAPL OR @Apple,$AAPL dip only momentarily....just an aberrati...
21,finalized,4,3,Mon Dec 01 23:12:40 +0000 2014,5.400000e+17,#AAPL OR @Apple,The JH Hines Staff with their newly issued @ap...
22,finalized,3,3,Mon Dec 01 23:43:14 +0000 2014,5.400000e+17,#AAPL OR @Apple,@robconeybeer: You need an IP portfolio to def...
27,finalized,4,3,Tue Dec 02 00:15:14 +0000 2014,5.400000e+17,#AAPL OR @Apple,Justice Department cites 18th century federal ...
29,finalized,3,3,Tue Dec 02 00:15:26 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
30,finalized,4,3,Tue Dec 02 00:16:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,Good be huge RT @thehill Justice Department ci...
31,finalized,3,3,Tue Dec 02 00:16:04 +0000 2014,5.400000e+17,#AAPL OR @Apple,@thehill @Apple i cite the 4th amendment as a ...
32,finalized,3,3,Tue Dec 02 00:16:27 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
33,finalized,4,5,Tue Dec 02 00:17:02 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @saxonidubom: @rwang0 @Apple Thanks...think...
34,finalized,3,3,Tue Dec 02 00:18:59 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
35,finalized,3,3,Tue Dec 02 00:22:26 +0000 2014,5.400000e+17,#AAPL OR @Apple,Way to stay relevant RT @thehill: Justice Depa...
36,finalized,6,3,Tue Dec 02 00:22:31 +0000 2014,5.400000e+17,#AAPL OR @Apple,Apple Inc. Flash Crash: What You Need to Know ...
38,finalized,3,3,Tue Dec 02 00:24:26 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
39,finalized,6,1,Tue Dec 02 00:24:47 +0000 2014,5.400000e+17,#AAPL OR @Apple,That flash crash really screwed with a lot of ...
40,finalized,3,3,Tue Dec 02 00:25:38 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @tra_hall: The JH Hines Staff with their ne...
42,finalized,3,3,Tue Dec 02 00:27:36 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
43,finalized,3,1,Tue Dec 02 00:28:38 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
45,finalized,3,3,Tue Dec 02 00:31:26 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
46,finalized,6,1,Tue Dec 02 00:32:42 +0000 2014,5.400000e+17,#AAPL OR @Apple,@thehill @Apple I cite the us constitution whe...
48,finalized,3,1,Tue Dec 02 00:38:41 +0000 2014,5.400000e+17,#AAPL OR @Apple,@thehill @Apple Wish we could prosecute the ad...
49,finalized,3,3,Tue Dec 02 00:39:47 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
50,finalized,3,3,Tue Dec 02 00:39:51 +0000 2014,5.400000e+17,#AAPL OR @Apple,@thehill @Apple Furthermore there are no provi...
51,finalized,3,1,Tue Dec 02 00:45:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,#AAPL:Here's why Apple dropped...http://t.co/q...
52,finalized,4,3,Tue Dec 02 00:45:22 +0000 2014,5.400000e+17,#AAPL OR @Apple,This one chart explains @tim_cook's affect on ...
53,finalized,3,3,Tue Dec 02 00:47:23 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
54,finalized,3,3,Tue Dec 02 00:47:46 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
55,finalized,4,3,Tue Dec 02 00:51:10 +0000 2014,5.400000e+17,#AAPL OR @Apple,"Final #AAPL #PutCallRatios for Monday, Decembe..."
56,finalized,3,3,Tue Dec 02 00:53:22 +0000 2014,5.400000e+17,#AAPL OR @Apple,#AAPL Launches Red #Apple Logo for World AIDS ...
59,finalized,3,1,Tue Dec 02 00:56:11 +0000 2014,5.400000e+17,#AAPL OR @Apple,@apple why doesn't your people explain precaut...
60,finalized,3,3,Tue Dec 02 00:56:43 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
61,finalized,3,3,Tue Dec 02 00:59:49 +0000 2014,5.400000e+17,#AAPL OR @Apple,@Quailman_ @Apple u was bored huh
62,finalized,3,3,Tue Dec 02 01:04:41 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @wagner_tim: @robconeybeer: You need an IP ...
64,finalized,3,1,Tue Dec 02 01:06:42 +0000 2014,5.400000e+17,#AAPL OR @Apple,@Apple made it clear today that I as a custome...
65,finalized,3,3,Tue Dec 02 01:06:58 +0000 2014,5.400000e+17,#AAPL OR @Apple,INSPI(RED) by @Apple and @tim_cook on #WorldAI...
66,finalized,4,3,Tue Dec 02 01:07:53 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
67,finalized,3,3,Tue Dec 02 01:09:53 +0000 2014,5.400000e+17,#AAPL OR @Apple,16GB @Apple #iPad Air 2 Retina WiFi Tablet $40...
69,finalized,3,1,Tue Dec 02 01:13:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,Why does @Apple force people to use its VPN bu...
70,finalized,3,1,Tue Dec 02 01:15:12 +0000 2014,5.400000e+17,#AAPL OR @Apple,Then how the hell did I take this screenshot? ...
71,finalized,3,3,Tue Dec 02 01:17:55 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill Department cites 18th century fede...
72,finalized,3,3,Tue Dec 02 01:22:40 +0000 2014,5.400000e+17,#AAPL OR @Apple,RT @thehill: Justice Department cites 18th cen...
73,finalized,6,1,Tue Dec 02 01:25:49 +0000 2014,5.400000e+17,#AAPL OR @Apple,Buy round lot on the open MT @WSJD #AAPL stock...
74,finalized,3,1,Tue Dec 02 01:36:18 +0000 2014,5.400000e+17,#AAPL OR @Apple,3G is draining my battery fix this @apple
75,finalized,3,not_relevant,Tue Dec 02 01:36:35 +0000 2014,5.400000e+17,#AAPL OR @Apple,My daughter's @Apple #iPod stolen. To the thie...

In [28]:
apple_tweets.dtypes

_unit_state            object
_trusted_judgments      int64
sentiment              object
date                   object
id                    float64
query                  object
text                   object
dtype: object

In [27]:
#To do that we may need to change the column type 
apple_tweets["_trusted_judgments"] = apple_tweets["_trusted_judgments"].astype(int)

#Note that when subsetting with multiple conditions, we must use the & operator
apple_tweets = apple_tweets[(apple_tweets["_trusted_judgments"] > 4) & (apple_tweets["sentiment"] != "not_relevant")]
apple_tweets.sort_values(by=["_trusted_judgments"], ascending=False)
apple_tweets

,_unit_state,_trusted_judgments,sentiment,date,id,query,text
15,finalized,6,3,Mon Dec 01 21:29:45 +0000 2014,5.400000e+17,#AAPL OR @Apple,#aapl @applenws Thanks to the non factual dumb...
36,finalized,6,3,Tue Dec 02 00:22:31 +0000 2014,5.400000e+17,#AAPL OR @Apple,Apple Inc. Flash Crash: What You Need to Know ...
39,finalized,6,1,Tue Dec 02 00:24:47 +0000 2014,5.400000e+17,#AAPL OR @Apple,That flash crash really screwed with a lot of ...
46,finalized,6,1,Tue Dec 02 00:32:42 +0000 2014,5.400000e+17,#AAPL OR @Apple,@thehill @Apple I cite the us constitution whe...
73,finalized,6,1,Tue Dec 02 01:25:49 +0000 2014,5.400000e+17,#AAPL OR @Apple,Buy round lot on the open MT @WSJD #AAPL stock...

In [24]:
apple_tweets.head(60)

,_unit_state,_trusted_judgments,sentiment,date,id,query,text
15,finalized,6,3,Mon Dec 01 21:29:45 +0000 2014,5.400000e+17,#AAPL OR @Apple,#aapl @applenws Thanks to the non factual dumb...
36,finalized,6,3,Tue Dec 02 00:22:31 +0000 2014,5.400000e+17,#AAPL OR @Apple,Apple Inc. Flash Crash: What You Need to Know ...
39,finalized,6,1,Tue Dec 02 00:24:47 +0000 2014,5.400000e+17,#AAPL OR @Apple,That flash crash really screwed with a lot of ...
46,finalized,6,1,Tue Dec 02 00:32:42 +0000 2014,5.400000e+17,#AAPL OR @Apple,@thehill @Apple I cite the us constitution whe...
73,finalized,6,1,Tue Dec 02 01:25:49 +0000 2014,5.400000e+17,#AAPL OR @Apple,Buy round lot on the open MT @WSJD #AAPL stock...

In [30]:
#Sometimes we may only want to keep rows with certain values 
apple_tweets['text'] = apple_tweets['text'].astype('str')
apple_tweets = apple_tweets[apple_tweets['text'].str.len() > 20]
apple_tweets

,_unit_state,_trusted_judgments,sentiment,date,id,query,text
15,finalized,6,3,Mon Dec 01 21:29:45 +0000 2014,5.400000e+17,#AAPL OR @Apple,#aapl @applenws Thanks to the non factual dumb...
36,finalized,6,3,Tue Dec 02 00:22:31 +0000 2014,5.400000e+17,#AAPL OR @Apple,Apple Inc. Flash Crash: What You Need to Know ...
39,finalized,6,1,Tue Dec 02 00:24:47 +0000 2014,5.400000e+17,#AAPL OR @Apple,That flash crash really screwed with a lot of ...
46,finalized,6,1,Tue Dec 02 00:32:42 +0000 2014,5.400000e+17,#AAPL OR @Apple,@thehill @Apple I cite the us constitution whe...
73,finalized,6,1,Tue Dec 02 01:25:49 +0000 2014,5.400000e+17,#AAPL OR @Apple,Buy round lot on the open MT @WSJD #AAPL stock...

In [33]:
#Renaming columns 
apple_tweets.rename({'_unit_state': 'unit_state', '_trusted_judgments': 'trusted_judgements'}, axis='columns', inplace=True)
apple_tweets

,_unit_id,_golden,unit_state,trusted_judgements,_last_judgment_at,sentiment,sentiment:confidence,date,id,query,sentiment_gold,text
0,623495513,True,golden,10,NaN,3,0.6264,Mon Dec 01 19:30:03 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\nnot_relevant,#AAPL:The 10 best Steve Jobs emails ever...htt...
1,623495514,True,golden,12,NaN,3,0.8129,Mon Dec 01 19:43:51 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\n1,RT @JPDesloges: Why AAPL Stock Had a Mini-Flas...
2,623495515,True,golden,10,NaN,3,1.0000,Mon Dec 01 19:50:28 +0000 2014,5.400000e+17,#AAPL OR @Apple,3,My cat only chews @apple cords. Such an #Apple...
3,623495516,True,golden,17,NaN,3,0.5848,Mon Dec 01 20:26:34 +0000 2014,5.400000e+17,#AAPL OR @Apple,3\n1,I agree with @jimcramer that the #IndividualIn...
4,623495517,False,finalized,3,12/12/14 12:14,3,0.6474,Mon Dec 01 20:29:33 +0000 2014,5.400000e+17,#AAPL OR @Apple,NaN,Nobody expects the Spanish Inquisition #AAPL
...,...,...,...,...,...,...,...,...,...,...,...,...
3881,623499442,True,golden,13,NaN,3,0.7757,Tue Dec 09 22:08:53 +0000 2014,5.420000e+17,#AAPL OR @Apple,5\n3,(Via FC) Apple Is Warming Up To Social Media -...
3882,623499450,True,golden,16,NaN,3,0.6225,Tue Dec 09 22:18:27 +0000 2014,5.420000e+17,#AAPL OR @Apple,3\n1,RT @MMLXIV: there is no avocado emoji may I as...
3883,623499486,True,golden,14,NaN,5,0.9347,Tue Dec 09 23:45:59 +0000 2014,5.420000e+17,#AAPL OR @Apple,5,@marcbulandr I could not agree more. Between @...
3884,623499514,True,golden,13,NaN,1,0.9230,Wed Dec 10 00:48:10 +0000 2014,5.420000e+17,#AAPL OR @Apple,1,My iPhone 5's photos are no longer downloading...
3885,623517290,True,golden,17,NaN,5,0.8938,Tue Dec 09 09:01:25 +0000 2014,5.420000e+17,#AAPL OR @Apple,5\n3\nnot_relevant,RT @SwiftKey: We're so excited to be named to ...

In [38]:
#grouping
#apple_tweets['trusted_judgements'] = apple_tweets['trusted_judgements'].astype("int64")
#apple_tweets.groupby(['unit_state'])['trusted_judgements'].std()
apple_tweets.groupby(['unit_state', 'date']).size()

unit_state  date
finalized   Fri Dec 05 00:02:35 +0000 2014    1
            Fri Dec 05 00:02:59 +0000 2014    1
            Fri Dec 05 00:04:39 +0000 2014    1
            Fri Dec 05 00:04:41 +0000 2014    1
            Fri Dec 05 00:05:43 +0000 2014    1
                                             ..
golden      Wed Dec 03 19:44:55 +0000 2014    1
            Wed Dec 03 22:01:20 +0000 2014    1
            Wed Dec 03 22:15:03 +0000 2014    1
            Wed Dec 03 23:03:02 +0000 2014    1
            Wed Dec 10 00:48:10 +0000 2014    1
Length: 3797, dtype: int64

In [39]:
#aggregating
pd.options.display.float_format = '{:.2f}'.format
apple_tweets['sentiment'] = apple_tweets['sentiment'].astype("int64")
apple_tweets.agg({"sentiment": ["mean", "median", "std"]})

ValueError: invalid literal for int() with base 10: 'not_relevant'

# Book wrangling snippet

In [ ]:
url="https://cssbook.net/d/guns-polls-dirty.csv"
d2=pd.read_csv(url)

# Option 1: clean with direct assignment
# Note that when creating a new column, 
# you have to use df["col"] rather than df.col 
d2["rep2"] = d2.rep.str.replace("[^0-9\\.]", "")
d2["rep2"] = pd.to_numeric(d2.rep2)
d2["Support2"]=d2.Support.fillna(d.Support.mean())

# Alternatively, clean with .assign 
# Note the need to use an anonymous function
# (lambda) to chain calculations
cleaned = d2.assign(
    rep2 = d2.rep.str.replace("[^0-9\\.]", ""),
    rep3 = lambda d2: pd.to_numeric(d2.rep2),
    Support2=d2.Support.fillna(d2.Support.mean()))


# Finally, you can create your own function 
def clean_num(x):
    x = re.sub("[^0-9\\.]", "", x)
    return int(x)

cleaned["rep3"] = cleaned.rep.apply(clean_num)
cleaned.head()

# Merging

In [126]:
apple_1 = pd.read_csv("apple_1.csv", sep=";")

In [139]:
apple_2 = pd.read_csv("apple_2.csv", sep=";")

In [122]:
apple_1.columns

Index(['_unit_id', 'unit_state'], dtype='object')

In [141]:
apple_2.columns

Index(['unit_id', '_golden', '_trusted_judgments', '_last_judgment_at',
       'sentiment', 'sentiment:confidence', 'date', 'id', 'query',
       'sentiment_gold', 'text'],
      dtype='object')

In [ ]:
#Merging on a column of the same dataset
#This will not run for these datasets. 
full = pd.merge(apple_1, apple_2, how="inner", on="unit_id")

In [ ]:
#Merging on two or more columns with the same name across both datasets
#This will not run for these datasets
full = pd.merge(apple_1, apple_2, how="inner", on=['column1', 'column2'])

In [150]:
#Merging on different keys - left
full = pd.merge(apple_1, apple_2, how="left", left_on='_unit_id', right_on='unit_id')

#We will need this line to merge succesfully 
#apple_2['unit_id'] = pd.to_numeric(apple_2['unit_id'], errors='coerce')

In [ ]:
#Merging on different keys - right
full = pd.merge(apple_1, apple_2, how="right", left_on='_unit_id', right_on='unit_id')

In [ ]:
#Merging on different keys - outer
full = pd.merge(apple_1, apple_2, how="outer", left_on='_unit_id', right_on='unit_id')

In [ ]:
#Merging on different keys - inner
full = pd.merge(apple_1, apple_2, how="inner", left_on='_unit_id', right_on='unit_id')

In [162]:
#Concatenating 
apple_3 = pd.read_csv("apple_3.csv", sep=';')
apple_4 = pd.read_csv("apple_4.csv", sep=';')

full = pd.concat([apple_3, apple_4])
len(apple_3)

In [ ]:
len(apple_4)

In [ ]:
#len(full) = len(apple_3) + (apple_4)
len(full)